### ISSUE TITLE
Saving custom "advanced game options" for a rom filename with invalid utf-8 characters causes ES to fail

### ISSUE THREAD

**Issue by n2qz** [batocera-linux/batocera-emulationstation#1391]
In Batocera v35, using the ES menus, I saved some options for a rom which had unzipped with some odd character set issue.  The filename for this rom contained a non-ASCII sequence which was not valid utf-8.  Afterwards, no roms could be loaded for any console, until these lines were removed.

```
apple2["Apple Panic (1981-06-02)(Br+▒derbund)[48K].woz"].core=mame
apple2["Apple Panic (1981-06-02)(Br+▒derbund)[48K].woz"].emulator=mame

```

Log file when trying to start any rom afterwards:

```
[root@nardole /userdata/system]# cat logs/es_launch_stderr.log
2023-01-26 21:40:07,394 ERROR (emulatorlauncher:571):<module> configgen exception:
Traceback (most recent call last):
  File "/usr/bin/emulatorlauncher", line 569, in <module>
    exitcode = main(args, maxnbplayers)
  File "/usr/bin/emulatorlauncher", line 97, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
  File "/usr/bin/emulatorlauncher", line 123, in start_rom
    system = Emulator(systemName, romConfiguration)
  File "/usr/lib/python3.10/site-packages/configgen/Emulator.py", line 25, in __init__
    recalSettings = UnixSettings(batoceraFiles.batoceraConf)
  File "/usr/lib/python3.10/site-packages/configgen/settings/unixSettings.py", line 31, in __init__
    file.write(open(self.settingsFile, encoding='utf_8_sig').read())
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.10/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 16478: invalid start byte
[root@nardole /userdata/system]#
```

**Comment by nadenislamarre** [comment]
hum. i don't know whats the expected behavior.
ignoring invalid lines only ? the full file is marked as invalid.

**Comment by fabricecaruso** [comment]
It's probably not directly related to Emulationstation, and it's a very particular case, so i'm closing this issue.
