### ISSUE TITLE
Batocera v38 - Duckstation emulator does not launch

### ISSUE THREAD

**Issue by Tasosdio** [batocera-linux/batocera-emulationstation#1569]
Hi everyone,

I have recently updated Batocera to v38, I have chosen duckstation to emulate psx games using. The first time I launched a game post upgrading to v38 was a success. Then I changed some settings (mostly video) and when I tried to launch a game again, duckstation fails to launch and returns to game list screen. The error logs are as follows:

#evmapy: no process found
2023-11-03 13:44:40,660 ERROR (emulatorlauncher:596):<module> configgen exception: 
Traceback (most recent call last):
  File "/usr/bin/emulatorlauncher", line 594, in <module>
    exitcode = main(args, maxnbplayers)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/emulatorlauncher", line 99, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/emulatorlauncher", line 262, in start_rom
    cmd = generator.generate(system, rom, playersControllers, guns, wheels, gameResolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/configgen/generators/duckstation/duckstationGenerator.py", line 32, in generate
    settings.read(settings_path)
  File "/usr/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/usr/lib/python3.11/configparser.py", line 1112, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/userdata/system/configs/duckstation/settings.ini' [line 64]: option 'Vsync' in section 'Display' already exists

2023-11-03 13:44:39,448 DEBUG (emulatorlauncher:124):start_rom Running system: psx
2023-11-03 13:44:39,454 INFO (Emulator.py:85):game_settings_name game settings name: Spider-Man (USA).cue
2023-11-03 13:44:39,454 DEBUG (unixSettings.py:21):__init__ Creating parser for /userdata/system/batocera.conf
2023-11-03 13:44:39,455 DEBUG (unixSettings.py:69):loadAll Looking for global.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,456 DEBUG (unixSettings.py:69):loadAll Looking for controllers.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,456 DEBUG (unixSettings.py:69):loadAll Looking for psx.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,457 DEBUG (unixSettings.py:69):loadAll Looking for psx.folder["/userdata/roms/psx/Spider Man"].* in /userdata/system/batocera.conf
2023-11-03 13:44:39,457 DEBUG (unixSettings.py:69):loadAll Looking for psx["Spider-Man (USA).cue"].* in /userdata/system/batocera.conf
2023-11-03 13:44:39,458 DEBUG (unixSettings.py:69):loadAll Looking for display.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,459 DEBUG (Emulator.py:46):__init__ uimode: Full
2023-11-03 13:44:39,460 DEBUG (unixSettings.py:69):loadAll Looking for psx-renderer.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,460 DEBUG (unixSettings.py:69):loadAll Looking for psx["Spider-Man (USA).cue"]-renderer.* in /userdata/system/batocera.conf
2023-11-03 13:44:39,461 DEBUG (emulatorlauncher:136):start_rom Settings: {'emulator': 'duckstation', 'core': 'duckstation', 'hud_support': True, 'videomode': 'max-1920x1080', 'ratio': '16/9', 'video_threaded': False, 'smooth': '1', 'shaderset': 'enhanced', 'rewind': False, 'bezel': 'none', 'forceNoBezel': False, 'gamemode_enable': False, 'video_frame_delay_auto': True, 'controllers.bluetooth.enabled': '1', 'controllers.ps3.enabled': '1', 'controllers.ps3.driver': 'bluez', 'controllers.xboxdrv.enabled': '0', 'controllers.xboxdrv.nbcontrols': '2', 'controllers.xarcade.enabled': '1', 'controllers.gpio.enabled': '0', 'controllers.gpio.args': 'map=1,2', 'controllers.db9.enabled': '0', 'controllers.db9.args': 'map=1', 'controllers.gamecon.enabled': '0', 'controllers.gamecon.args': 'map=1', 'videooutput': 'HDMI-0', 'integerscale': '1', 'retroachievements': '0', 'retroachievements.hardcore': '0', 'retroachievements.leaderboards': '0', 'retroachievements.verbose': '0', 'retroachievements.screenshot': '0', 'retroachievements.sound': 'none', 'autosave': '1', 'bezel_stretch': '1', 'retroachievements.challenge_indicators': '0', 'retroachievements.encore': '0', 'retroachievements.richpresence': '0', 'game_fixes_pcsx': 'disabled', 'beetle_psx_internal_resolution': '8x', 'duckstation_ofp': 'true', 'duckstation_PatchFastBoot': 'false', 'duckstation_vsync': 'false', 'showFPS': 'false', 'uimode': 'Full', 'emulator-forced': True, 'core-forced': True}
2023-11-03 13:44:39,461 DEBUG (emulatorlauncher:138):start_rom emulator: duckstation, core: duckstation
2023-11-03 13:44:39,461 INFO (emulatorlauncher:154):start_rom guns disabled.
2023-11-03 13:44:39,461 INFO (emulatorlauncher:166):start_rom wheels disabled.
2023-11-03 13:44:39,545 DEBUG (emulatorlauncher:190):start_rom current video mode: 1920x1080.60.00
2023-11-03 13:44:39,545 DEBUG (emulatorlauncher:191):start_rom wanted video mode: max-1920x1080
2023-11-03 13:44:39,545 DEBUG (videoMode.py:18):changeMode setVideoMode(max-1920x1080): ['batocera-resolution', 'setMode', 'max-1920x1080']
2023-11-03 13:44:39,691 DEBUG (videoMode.py:23):changeMode 
2023-11-03 13:44:39,738 DEBUG (emulatorlauncher:203):start_rom resolution: 1920x1080
2023-11-03 13:44:39,738 DEBUG (emulatorlauncher:472):callExternalScripts calling external script: ['/usr/share/batocera/configgen/scripts/rotation_fix.sh', 'gameStart', 'psx', 'duckstation', 'duckstation', '/userdata/roms/psx/Spider Man/Spider-Man (USA).cue']
2023-11-03 13:44:39,740 DEBUG (Evmapy.py:43):__prepare evmapy on /usr/share/evmapy/psx.duckstation.keys
2023-11-03 13:44:39,744 DEBUG (Evmapy.py:83):__prepare config file for keysfile is /var/run/evmapy/event12.json (from /usr/share/evmapy/psx.duckstation.keys)
/var/run/evmapy/ready MODIFY 
2023-11-03 13:44:40,606 DEBUG (videoMode.py:18):changeMode setVideoMode(1920x1080.60.00): ['batocera-resolution', 'setMode', '1920x1080.60.00']
2023-11-03 13:44:40,660 DEBUG (videoMode.py:23):changeMode 1920x1080.60.00
2023-11-03 13:44:41,661 DEBUG (emulatorlauncher:605):<module> Exiting configgen with status -1

​

[es_launch_stdout.log](https://github.com/batocera-linux/batocera-emulationstation/files/13251992/es_launch_stdout.log)
[es_launch_stderr.log](https://github.com/batocera-linux/batocera-emulationstation/files/13251993/es_launch_stderr.log)

Does anybody know how can I fix this?

Thank you very much.

**Comment by fabricecaruso** [comment]
Not related to EmulationStation sorry. 
Re-create an issue in batocera-linux repository.
