### ISSUE TITLE
In beta x86_64 image from 14th of October shaders do not work

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#609]
In menu there are not just names of shaders but also paths. And it does not work.

**Comment by mistepien** [comment]
This is what I found in es_launch_stderr.log:

> 2020-10-16 10:43:07 INFO (emulatorlauncher.py:88):main(): Running system: mastersystem
2020-10-16 10:43:07 DEBUG (unixSettings.py:21):__init__(): Creating parser for /userdata/system/batocera.conf
2020-10-16 10:43:07 DEBUG (unixSettings.py:82):loadAll(): Looking for global.* in /userdata/system/batocera.conf
2020-10-16 10:43:07 DEBUG (unixSettings.py:82):loadAll(): Looking for mastersystem.* in /userdata/system/batocera.conf
2020-10-16 10:43:07 DEBUG (unixSettings.py:82):loadAll(): Looking for mastersystem["Aladdin (Europe).zip"].* in /userdata/system/batocera.conf
2020-10-16 10:43:07 INFO (Emulator.py:33):__init__(): uimode: Full
2020-10-16 10:43:07 ERROR (emulatorlauncher.py:245):<module>: configgen exception: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py", line 243, in <module>
    exitcode = main(args, maxnbplayers)
  File "/usr/lib/python2.7/site-packages/configgen/emulatorlauncher.py", line 89, in main
    system = Emulator(systemName, args.rom)
  File "/usr/lib/python2.7/site-packages/configgen/Emulator.py", line 38, in __init__
    self.renderconfig = Emulator.get_generic_config(self.name, "/usr/share/batocera/shaders/configs/" + self.config["shaderset"] + "/rendering-defaults.yml", "/usr/share/batocera/shaders/con
figs/" + self.config["shaderset"] + "/rendering-defaults-arch.yml")
  File "/usr/lib/python2.7/site-packages/configgen/Emulator.py", line 71, in get_generic_config
    systems_default = yaml.load(file(defaultyml, "r"), Loader=yaml.FullLoader)
IOError: [Errno 2] No such file or directory: u'/usr/share/batocera/shaders/configs//usr/share/batocera/shaders/configs/zfast/rendering-defaults.yml'
2020-10-16 10:43:08 INFO (emulatorlauncher.py:247):<module>: Exiting configgen with status -1

**Comment by mistepien** [comment]
I made a dirty workaound just like that:

```
# pwd
/usr/share/batocera/shaders/configs/usr/share/batocera/shaders/configs
# ls -l
total 0
lrwxrwxrwx    1 root     root            41 Oct 16 10:50 zfast -> /usr/share/batocera/shaders/configs/zfast

```

**Comment by fabricecaruso** [comment]
Should be fixed with my recent PR. Wait for the next beta
