### ISSUE TITLE
BATOCERA - does not open any game

### ISSUE THREAD

**Issue by alankon** [batocera-linux/batocera-emulationstation#976]
I have a batch ready, but no game opens, in no emulator configuration,
the only mistake I caught was this:

2021-09-05 17:14:03 INFO (emulatorlauncher.py:129):main(): Running system: psx
2021-09-05 17:14:03 DEBUG (unixSettings.py:20):__init__(): Creating parser for /userdata/system/batocera.conf
2021-09-05 17:14:03 ERROR (emulatorlauncher.py:324):<module>: configgen exception: 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/configgen/emulatorlauncher.py", line 322, in <module>
    exitcode = main(args, maxnbplayers)
  File "/usr/lib/python3.9/site-packages/configgen/emulatorlauncher.py", line 130, in main
    system = Emulator(systemName, args.rom)
  File "/usr/lib/python3.9/site-packages/configgen/Emulator.py", line 26, in __init__
    recalSettings = UnixSettings(batoceraFiles.batoceraConf)
  File "/usr/lib/python3.9/site-packages/configgen/settings/unixSettings.py", line 30, in __init__
    file.write(io.open(self.settingsFile, encoding='utf_8_sig').read())
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.9/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 14: invalid continuation byte
2021-09-05 17:14:04 INFO (emulatorlauncher.py:326):<module>: Exiting configgen with status -1

can you help me?
I didn't find a place for questions

**Comment by fabricecaruso** [comment]
Not related to emulationstation, but to batocera.linux
